algoritmo "Desafio 13"
// Função : "Calcular valor da conta por pessoa"
// Autor :  Ilson de Bacellar Jr
// Data : 16/03/2022
// Seção de Declarações 
var
  numPessoas: inteiro
  mesa: inteiro
  totalIndividual: real
inicio

   numPessoas <- 5
   mesa <- 222
   totalIndividual <- 20,00
   produto <- 3
   
   para produto >= 1 ou <= 5 faça

        total

   escreval ("Cada uma das", numPessoas," pessoas da mesa", mesa," deve pagar R$", totalIndividual, " de conta.")

fimalgoritmo
